### PR TITLE
More translating!

### PR DESCRIPTION
**Pull request by BreakinBenny**
It's took me time, but here we go. If the translation requires improvement, go for it!

### CODE REVIEW

**Comment by HapLifeMan** [comment]
Thank you so much for your work! It looks like you edited an old version of the translations, could you please see [these up-to-date files](https://github.com/affinitweet/translations/tree/master/sv) and replace your new translations into them? 😊

**Comment by BreakinBenny** [comment]
Oh man... Yes, I'll get to it.

**Comment by HapLifeMan** [comment]
Perfect for the back file, the front file is still outdated, I suggest you to take the current `front.js` file in your language then copy/paste what you modified 😊

**Comment by BreakinBenny** [comment]
There we go: https://github.com/affinitweet/translations/pull/28

**Comment by HapLifeMan** [comment]
Translations are online, thank you again @BreakinBenny! 😊

**Pull request closed without merging**
