### PR TITLE
 Create pt-br.json 

### PR DESCRIPTION
**Pull request by allanf181**

### CODE REVIEW

**Comment by HapLifeMan** [comment]
Hi @allanf181, you did a very good job, thank you very much for your work!

This is the first PR for this locale, I'll merge it as soon as possible.
Sorry for your work @Igormandello but you weren't fast enough to make a PR 😅
By the way, can you review this translation? I'll add you as a contributor on this repo 😉

**Comment by Igormandello** [comment]
@HapLifeMan, that's okay hahaha, I took a look and there are some things that in my case I translated in another way, like the features name, but of course I can review the translations =)

**Comment by HapLifeMan** [comment]
Features name are not translatable as described in the README 😊

**Comment by igor-mandello-playkids** [comment]
@HapLifeMan oh, okay, I thought the translation of the feature names was optional, not prohibited

**Comment by allanf181** [comment]
Any deadline for the translation to be added?

**Comment by HapLifeMan** [comment]
Hi @allanf181, I will add this translation in the next release 😉
I'm currently very busy but I'll do it as soon as possible, maybe by the end of March or April.

I'll keep you updated about that!

**Comment by allanf181** [comment]
I got a little confused with Secret Crush's tweet text, it shouldn't be ``{{user}} secretly loves me!`` instead of ``{{user}} secretly loves you!``?

**Comment by HapLifeMan** [comment]
Hi @allanf181, I'm glad to say that Portuguese is now available on https://affinitweet.com! 🎉

Nice catch, this is a misspelling. This will be improved in the next big update 😉

**Comment by allanf181** [comment]
https://github.com/affinitweet/translations/commit/c0ece56682ce50e0ae93b8c451ef9f7ff8554813 the correction of the misspelling in portuguese

**Comment by HapLifeMan** [comment]
Thanks! I'll fix it in the next release 😅

**Pull request merged**
