### PR TITLE
new id.json

### PR DESCRIPTION
**Pull request by asyariruby**
Hello, I'm translating a json file from EN to indonesian.
Will receive my file.

### CODE REVIEW

**Comment by HapLifeMan** [comment]
Thank you very much @asyariruby!

I modify your file because it was malformed, my first commit was a bad copy/paste.

Can you check these lignes please and confirm that's good for you or edit them?

- Lines `9`, `15`, `18`, `25-29`, `34`, `36`, `38`, `41-46`, `48`, `50-52` : no upper case letter at the start of the string?
- Lies `31-33`: no lower case letter at the start of the string?
- Line `30`: it should be something like `0 (second) | 1 (second) | 2 (seconds)`
- Lines `55`, `83`: no translation for "auto-tweet"?
- Line `65`: no translation for "Emojis pack"?
- Line `88`: no translation for "Not enough data"?
- Line `206`: no translation for "Responsive"?
- Line `260`: no translation for "Lily-of-the-Valley"? (it's a flower name)
- Line `291`: no translation for "This year you're mine"?

**Comment by asyariruby** [comment]
do I need to edit again? because there is already a file changes, please explanation

**Comment by HapLifeMan** [comment]
Click on this link then start editing the file 🙂
https://github.com/asyariruby/translations/edit/patch-1/locales/id.json

**Comment by asyariruby** [comment]
I've done the repair, please check

**Comment by HapLifeMan** [comment]
It seems better now!

Last things to check lines `19-24`: is it the same as in english?

**Comment by asyariruby** [comment]
looks like i'm all ready.

**Comment by HapLifeMan** [comment]
Yes! Thank you very much for your translation :)

**Comment by asyariruby** [comment]
I am very happy to contribute

**Pull request merged**
