### PR TITLE
Turkish Translation

### PR DESCRIPTION
**Pull request by mugurcagdas**
Hello,
I translated json file from EN to TUR.
Proofread, there is no fault, double checked.
Thanks.

### CODE REVIEW

**Comment by HapLifeMan** [comment]
Thank you very much! :D

**Comment by mugurcagdas** [comment]
Will you merge this file?
Thanks.

**Comment by HapLifeMan** [comment]
Of course I'll do!
You don't want to be credited as the author?

**Comment by mugurcagdas** [comment]
Actually it is not matter. This translate for Turkish users, this is important for me.
Thanks for your reply.

**Comment by mugurcagdas** [comment]
@HapLifeMan  Oh sorry, I didn't understand what you mention. 
I updated author part now. 
Thanks

**Comment by asyariruby** [comment]
I want to translate language english to indonesian, can I translate

**Comment by asyariruby** [comment]
I want to translate language english to indonesian, can I translate

**Comment by HapLifeMan** [comment]
No problem, I fixed some typo too :)

Can you confirm that there's no space before the `:`, and a space before `...` in your language?
Also, can you translate the lines `23-24` please? :)

After that, that'll be OK to merge and add it to the next release!

**Comment by mugurcagdas** [comment]
Hello,
I updated tr.json file according to your wishes. there's no space before the ` :` and `...` now.
Also, I translated lines 23-24.
Thanks.

**Comment by HapLifeMan** [comment]
Thank you! :)

**Pull request merged**
