### PR TITLE
Filipino Translation.agentzero1.json

### PR DESCRIPTION
**Pull request by agentzero1**
Filipino translation

### CODE REVIEW

**Comment by HapLifeMan** [comment]
Thank you very much for you translation! 😁
Don't forget to replace by your name in the `__translation.author` section :)
Please edit and re-check [this file](https://github.com/agentzero1/translations/blob/1c9f9a2ed115799b1c812b826128c5a81e8be7dd/locales/tl.json) before I merge it :)

**Comment by agentzero1** [comment]
Is this correct ?

**Comment by agentzero1** [comment]
Im waiting for your positive response

**Comment by HapLifeMan** [comment]
Please read the Precisions secition in the README and check the file, some content is incorrect.
And add your firstname and lastname into the `author` section :)

**Comment by agentzero1** [comment]
Here's my updated files.

**Comment by HapLifeMan** [comment]
Can you confirm that there's no space before the`:`, and a space before `...` in your language?
Can you translate occurrences of `Lily-of-the-Valley` and re-check the file?

**Comment by agentzero1** [comment]
Sir I fixed it and theres no direct translation of  `Lily-of-the-Valley` .

**Pull request closed without merging**
