### PR TITLE
German Language Support Added

### PR DESCRIPTION
**Pull request by ByFxbian**
I just added the **fully** **translated** _german language_, and also translated german into every other language! I hope you like it!

### CODE REVIEW

**Comment by HapLifeMan** [comment]
Thank you so much for you work! I will merge this and release in the following hours once tested locally 😊

**Comment by ByFxbian** [comment]
Nice! I hope there are no errors 👍🏻 If there are, please tell me so I can fix them instantly 😄

**Comment by HapLifeMan** [comment]
No error and everything is live!

You can try on https://affinitweet.com by yourself and see if everything looks as you want 😊
I will publish a tweet to thank you on our Twitter account by mentioning you!

**Comment by ByFxbian** [comment]
Wow nice! That was my first time helping on translating something, so i was pretty nervous, because i thought i maybe would get some errors xd But nice to see that there were no errors 👀

**Comment by ByFxbian** [comment]
Oh wait, i just found something, lemme fix that really quick xd I just saw a typo on ur profile page lol

**Comment by HapLifeMan** [comment]
Don't worry everything is fine, I made some changes on your files, could you use the updated ones to do your fixes?

**Comment by ByFxbian** [comment]
Oh yeah sure :P

**Comment by ByFxbian** [comment]
Do i have to make a new pull request to update the fixes? ^^

**Comment by HapLifeMan** [comment]
Yes you need to pull the changes of the main repository then do a new PR!

**Comment by HapLifeMan** [comment]
Hello @ByFxbian, I hope you're going well! 😊

I published a new release of Affinitweet a few days ago and I was wondering if were still motivated to translate Affinitweet because there's new strings to update and translate...

By the way, I changed the way how translations are made and now I'm using a open-localization tool. It's way better for translators and me to translate, maintain and integrate on the website!

If you're interested in updating your translations, could you please send a [DM on Twitter](https://twitter.com/affinitweet_) and asking for Thomas, with an email address where I can send you an invite to the translation platform?

Thank you so much!

**Pull request merged**
