### PR TITLE
Create es.json

### PR DESCRIPTION
**Pull request by kobernyk**
Translation from English to Spanish

### CODE REVIEW

**Comment by HapLifeMan** [comment]
Amazing work! Thank you so much for your translation @kobernyk! 😁

**Comment by HapLifeMan** [comment]
Can you tell me if everything is okay once integrated?

Especially these pages:
- https://affinitweet.com/privacy
- https://affinitweet.com/legal
- https://affinitweet.com/new

Thank you!

**Comment by kobernyk** [comment]
It looks great!

**Comment by HapLifeMan** [comment]
Hello @kobernyk, I hope you're going well! 😊

I published a new release of Affinitweet a few days ago and I was wondering if were still motivated to translate Affinitweet because there's new strings to update and translate...

By the way, I changed the way how translations are made and now I'm using a open-localization tool. It's way better for translators and me to translate, maintain and integrate on the website!

If you're interested in updating your translations, could you please send a [DM on Twitter](https://twitter.com/affinitweet_) and asking for Thomas, with an email address where I can send you an invite to the translation platform?

Thank you so much!

**Pull request merged**
