### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by QkeleQ10**
I translated Affinitweet to Dutch! Hopefully you'll be getting more Dutch visitors. I left some of the Terms of Service and Legal page for someone else to translate / for me to translate later, since I don't really feel like I can translate that without losing important information at this point in time.

### CODE REVIEW

**Comment by HapLifeMan** [comment]
**Thank you so much for your work Quinten!** A last thing before merging: could you please add your locale name to other translation files? (for example add `dutch: "Dutch",` into the `en/front.js` file then `_lg:` object, thanks!

No problem for the terms page, it will fallback to english translations until translated 😊

**Comment by QkeleQ10** [comment]
Alright, done @HapLifeMan! :D Excuse my commit names please haha

**Comment by HapLifeMan** [comment]
Perfect thanks! 😊
I will merge it and deploy tomorrow 🇳🇱🇳🇱🇳🇱

**Comment by HapLifeMan** [comment]
Your translations are now live, thanks again for your hard work!
You can check if you want on https://affinitweet.com 😊

**Comment by HapLifeMan** [comment]
Hello @QkeleQ10, I hope you're going well! 😊

I published a new release of Affinitweet a few days ago and I was wondering if were still motivated to translate Affinitweet because there's new strings to update and translate...

By the way, I changed the way how translations are made and now I'm using a open-localization tool. It's way better for translators and me to translate, maintain and integrate on the website!

If you're interested in updating your translations, could you please send a [DM on Twitter](https://twitter.com/affinitweet_) and asking for Thomas, with an email address where I can send you an invite to the translation platform?

Thank you so much!

**Pull request merged**
