### PR TITLE
Update front.js

### PR DESCRIPTION
**Pull request by BreakinBenny**
How about this?

### CODE REVIEW

**Comment by HapLifeMan** [comment]
! There are still a few todos but that's a very good progress 😄

**Comment by BreakinBenny** [comment]
I don't even know what's missing now.

**Comment by HapLifeMan** [comment]
Lines with // TODO on my last commit!

**Comment by HapLifeMan** [comment]
That's perfect @BreakinBenny, thank you so much! I will deploy it later today 😊

**Pull request merged**
