### PR TITLE
Added Swedish language

### PR DESCRIPTION
**Pull request by BreakinBenny**

### CODE REVIEW

**Comment by HapLifeMan** [comment]
Hey @BreakinBenny, thank you very much for your work! 👏🏻
I will review your PR in the next days 😊

**Comment by BreakinBenny** [comment]
@HapLifeMan No problem. Do note I haven't translated the FAQ, legal, Terms of Service, nor the data and privacy parts!

**Comment by HapLifeMan** [comment]
The FAQ page has been deprecated and will be remove in the following days, no need to translate them.
Legal, TOS and Privacy pages are a "good to have", if you have time to translate them it would be awesome!

**Comment by HapLifeMan** [comment]
Thank you again Fox, your changes has been merged and are now live on affinitweet.com!
I also updated some strings (I think there's some new), so if you have some time, feel free to update them 😊

**Pull request merged**
