### PR TITLE
I would like to help

### PR DESCRIPTION
**Pull request by MichaelBonfanti**
I would like to help translate your site into my language which is Italian, I have already started translating the back.js file

[it.zip](https://github.com/affinitweet/translations/files/6279452/it.zip)

### CODE REVIEW

**Comment by HapLifeMan** [comment]
Hey Michael, thanks for your help and work!
I'll be glad to deploy your translations to make them available worldwide 😊

Let me know if you have any questions!

**Comment by MichaelBonfanti** [comment]
thank you so much

**Comment by MichaelBonfanti** [comment]
[it.zip](https://github.com/affinitweet/translations/files/6789809/it.zip)

I have completed the Italian translation

**Comment by HapLifeMan** [comment]
Hello Michael, thanks for you work! Can you please add your changes to this PR so I'll be able to merge?

**Comment by MichaelBonfanti** [comment]
Here are the complete translations
[it.zip](https://github.com/affinitweet/translations/files/6808752/it.zip)

**Pull request closed without merging**
